# -*- coding: utf-8 -*-
"""SquadT5WithKey.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12nnup9nBDIy7yk5AVYJACP2mTXoCDZgG
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install datasets
# !pip install simpletransformers

from simpletransformers.t5 import T5Model

from datasets import load_dataset
raw_datasets = load_dataset('squad')

import pandas as pd

train_list = list()
for i in range(len(raw_datasets['train'])):
  new_record = dict()
  new_record['input_text'] = '%s answer: %s' % (raw_datasets['train'][i]['context'], raw_datasets['train'][i]['answers']['text'][0])
  new_record['target_text'] = raw_datasets['train'][i]['question']
  new_record['prefix'] = 'generate_question'
  train_list.append(new_record)

validation_list = list()
for i in range(len(raw_datasets['validation'])):
  new_record = dict()
  new_record['input_text'] = '%s answer: %s' % (raw_datasets['validation'][i]['context'], raw_datasets['validation'][i]['answers']['text'][0])
  new_record['target_text'] = raw_datasets['validation'][i]['question']
  new_record['prefix'] = 'generate_question'
  validation_list.append(new_record)

train_df = pd.DataFrame.from_dict(train_list)
validation_df = pd.DataFrame.from_dict(validation_list)

train_df.head()

validation_df.head()

model_args = {
    "reprocess_input_data": True,
    "overwrite_output_dir": True,
    "max_seq_length": 128,
    "train_batch_size": 8,
    "num_train_epochs": 1,
    "save_eval_checkpoints": True,
    "save_steps": -1,
    "use_multiprocessing": False,
    "evaluate_during_training": True,
    "evaluate_during_training_steps": 15000,
    "evaluate_during_training_verbose": True,
    "fp16": False,
    'special_tokens_list': ['answer'],
    "wandb_project": "MCQ Generation Using T5 and Squad",
}

model = T5Model("t5", "t5-base", args=model_args)

model.train_model(train_df, eval_data=validation_df)

model = T5Model("t5", "outputs/best_model", args=model_args)

to_predict = [
    """generate_question: In 1971, George Lucas wanted to film an adaptation of the Flash Gordon serial, but could not obtain the rights, so he began developing his own space opera. 
    answer: Geroge Lucas""",
]

predictions = model.predict(to_predict)

predictions

!tar -zcvf model_with_key.tar.gz outputs/best_model/

from google.colab import drive
drive.mount('/content/drive')

!cp model_with_key.tar.gz /content/drive/MyDrive/Models

# Extract
!tar -zxvf model_with_key.tar.gz